version: '3.1'
services:
  orderapp:
    image: orderapp:latest
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - orders_service:/app
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sapat1925
      MYSQL_DATABASE: order_db
      MYSQL_USER: abhi
      MYSQL_PASSWORD: abd781997
    ports:
      - "3309:3306"
    volumes:
      - dbdata_order:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Sapat1925
    ports:
      - "8081:80"
volumes:
  dbdata_order:
  orders_service:

